version: '3.8'

services:
  # Frontend React App
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - GENERATE_SOURCEMAP=false
    depends_on:
      - backend
    networks:
      - bankqu-network
    stdin_open: true
    tty: true
    restart: unless-stopped

  # Backend Laravel API with SQLite
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    environment:
      - APP_NAME=BankQu
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - CACHE_STORE=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - QUEUE_CONNECTION=database
      - SANCTUM_STATEFUL_DOMAINS=localhost:3000,127.0.0.1:3000
      - SESSION_DOMAIN=localhost
      - MAIL_MAILER=log
      - BROADCAST_CONNECTION=log
      - FILESYSTEM_DISK=local
    networks:
      - bankqu-network
    restart: unless-stopped

networks:
  bankqu-network:
    driver: bridge